### ISSUE TITLE
Donating household/kitchen supplies etc. for Appsterdam HQ

### ISSUE THREAD

**Issue by SidelineNoob** [Appsterdam/open#78]
I have a bunch of supplies gathering dust here, that may be useful at the HQ. But before I just bring everything over, it might be smart to check if won't just be gathering dust there as well.
Is there a list somewhere with what we have and need? If not, should I make one?

A short list of what I have here:
* a set of melamine plates and cups
* a hodgepodge of mugs
* a set of coffee cups with spoons
* probably some spare cleaning supplies

If I start looking, I probably have a bunch of bowls in various sizes too and who knows what else.

**Comment by judykitteh** [comment]
Long overdue reply, but if you still have these items, feel free to drop them off at A Lab or my house.
