### ISSUE TITLE
Looking for new coordinator for Speakers Bureau and WWLL

### ISSUE THREAD

**Issue by matteom** [Appsterdam/open#92]
2014 will see my departure from my role as coordinator of the Appsterdam Speakers bureau after more than two years. So, we are looking for a replacement.

The duties are mainly limited to the organization of the WWLL every week (plus some occasional duties). Since the sceduling of the speakers is taken care by another person, this boils down to prepare the venue and introduce the speaker (more details can be found [here](https://github.com/Appsterdam/open/blob/master/events/WeeklyWednesdayLunchtimeLectures.md)).

This role gives a good opportunity to be involved directly in the community and get to know the (sometimes famous) speakers that participate to our lectures, as well as the attendees.

I will cover the role until the end of January 2014, so we need someone as of February.

**Comment by judykitteh** [comment]
Mike is now running WWLL solo.
